options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/green-energy-tracker-cloud/ci-cd-templates.git ci-template
        echo "================ LISTA FILE SCARICATI ================"
        ls -R ci-template
        echo "======================================================"
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud builds submit . \
          --config=ci-template/cloudbuild-template.yaml \
          --substitutions=_IMAGE_NAME="site-bff",_SERVICE_NAME="site-bff"