steps:

  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        git clone https://github.com/green-energy-tracker-cloud/ci-cd-templates.git

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud builds submit . \
          --config=ci-config/path/to/cloudbuild.yaml \
          --substitutions=_IMAGE_NAME="site-bff",_SERVICE_NAME="site-bff"