substitutions:
  _ARTIFACT_REGISTRY_REPO: "microservices-repo"
  _IMAGE_NAME: "site-bff"
  _LOCATION: "us-east1"

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  volumes:
    - name: 'maven-cache'
      path: '/root/.m2'

steps:
  - id: "Unit Test"
    name: 'maven:3.9-eclipse-temurin-21'
    args: [ 'mvn', 'clean', 'test' ]

  - id: "Start Dependencies for Integration Test"
    name: 'docker/compose:1.29.2'
    args: [ '-f', 'docker-compose.yml', '-f', 'docker-compose.ci.yml', 'up', '-d' ]
    waitFor:
      - "Unit Test"

  - id: "Wait for Firestore"
    name: 'ubuntu'
    args: [ 'sh', '-c', 'sleep 10' ]
    waitFor: [ "Start Dependencies for Integration Test" ]

  # STEP DI DEBUG TEMPORANEO
  - id: "Debug Docker"
    name: 'docker'
    args: ['ps', '-a'] # Vediamo se firestore è "Up" o "Exited"
    waitFor: ['Wait for Firestore']

  - id: "Integration Test"
    name: 'maven:3.9-eclipse-temurin-21'
    env:
      - 'FIRESTORE_EMULATOR_HOST=localhost:8695'
      - 'PUBSUB_EMULATOR_HOST=localhost:8085'
    args: [ 'mvn', 'verify' ]
    waitFor:
      - "Wait for Firestore"

  - id: "Stop Dependencies"
    name: 'docker/compose:1.29.2'
    args: [ 'down' ]