server:
  port: 8080
spring:
  application:
    name: site-bff
  pagination:
    default:
      page: 0
      size: 10
  data:
    redis:
      prefix-key: site
      ttl-seconds: 3600
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      repositories:
        enabled: false
  cloud:
    gcp:
      pubsub:
        topic:
          site-events: site-events
