apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: site-bff
build:
  artifacts:
    - image: site-bff
manifests:
  rawYaml:
    - service-prod.yaml

deploy:
  cloudrun: {}

profiles:
  - name: prod
    manifests:
      rawYaml:
        - service-prod.yaml